-- Phase 4: email delivery audit trail + closed-record protection
-- Run AFTER Phase 3 has been installed successfully.

create table if not exists public.confirmation_audit_events (
  id bigint generated by default as identity primary key,
  confirmation_id uuid not null references public.confirmation_requests(id) on delete cascade,
  adviser_id uuid references auth.users(id) on delete set null,
  event_type text not null check (event_type in (
    'CREATED',
    'EMAIL_SENT',
    'CLIENT_VIEWED',
    'CLIENT_SIGNED',
    'ADVISER_SIGNED',
    'CLOSED'
  )),
  actor_type text not null check (actor_type in ('ADVISER', 'CLIENT', 'SYSTEM')),
  actor_label text,
  metadata jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now()
);

create index if not exists confirmation_audit_events_confirmation_id_idx
  on public.confirmation_audit_events(confirmation_id, occurred_at);

alter table public.confirmation_audit_events enable row level security;

-- Adviser may read audit events only for confirmations they own.
drop policy if exists "Adviser can read own confirmation audit" on public.confirmation_audit_events;
create policy "Adviser can read own confirmation audit"
on public.confirmation_audit_events
for select
to authenticated
using (
  exists (
    select 1
    from public.confirmation_requests c
    where c.id = confirmation_id
      and c.adviser_id = auth.uid()
  )
);

-- Adviser may append events only to confirmations they own.
-- No UPDATE or DELETE policy is created: the audit table is append-only to normal clients.
drop policy if exists "Adviser can append own confirmation audit" on public.confirmation_audit_events;
create policy "Adviser can append own confirmation audit"
on public.confirmation_audit_events
for insert
to authenticated
with check (
  adviser_id = auth.uid()
  and exists (
    select 1
    from public.confirmation_requests c
    where c.id = confirmation_id
      and c.adviser_id = auth.uid()
  )
);

-- Seed CREATED events for existing Phase 3 records that do not already have one.
insert into public.confirmation_audit_events (
  confirmation_id, adviser_id, event_type, actor_type, actor_label, metadata, occurred_at
)
select
  c.id,
  c.adviser_id,
  'CREATED',
  'ADVISER',
  c.adviser_name,
  jsonb_build_object('reference_no', c.reference_no),
  c.created_at
from public.confirmation_requests c
where not exists (
  select 1
  from public.confirmation_audit_events a
  where a.confirmation_id = c.id
    and a.event_type = 'CREATED'
);

-- Automatically append CREATED / ADVISER_SIGNED / CLOSED events.
create or replace function public.audit_confirmation_request_changes()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    insert into public.confirmation_audit_events (
      confirmation_id, adviser_id, event_type, actor_type, actor_label, metadata, occurred_at
    ) values (
      new.id,
      new.adviser_id,
      'CREATED',
      'ADVISER',
      new.adviser_name,
      jsonb_build_object('reference_no', new.reference_no),
      new.created_at
    );
    return new;
  end if;

  if tg_op = 'UPDATE'
     and old.status is distinct from new.status
     and new.status = 'CLOSED' then
    insert into public.confirmation_audit_events (
      confirmation_id, adviser_id, event_type, actor_type, actor_label, metadata, occurred_at
    ) values (
      new.id,
      new.adviser_id,
      'ADVISER_SIGNED',
      'ADVISER',
      new.adviser_name,
      jsonb_build_object('reference_no', new.reference_no),
      coalesce(new.adviser_signed_at, now())
    );

    insert into public.confirmation_audit_events (
      confirmation_id, adviser_id, event_type, actor_type, actor_label, metadata, occurred_at
    ) values (
      new.id,
      new.adviser_id,
      'CLOSED',
      'SYSTEM',
      'TSI Confirmation Portal',
      jsonb_build_object('reference_no', new.reference_no),
      coalesce(new.adviser_signed_at, now())
    );
  end if;

  return new;
end;
$$;

drop trigger if exists confirmation_request_audit_trigger on public.confirmation_requests;
create trigger confirmation_request_audit_trigger
after insert or update on public.confirmation_requests
for each row execute function public.audit_confirmation_request_changes();

-- A closed confirmation is immutable to ordinary adviser updates.
drop policy if exists "Adviser can update own confirmations" on public.confirmation_requests;
create policy "Adviser can update own confirmations"
on public.confirmation_requests
for update
to authenticated
using (
  auth.uid() = adviser_id
  and status <> 'CLOSED'
)
with check (
  auth.uid() = adviser_id
  and status in ('AWAITING_CLIENT', 'AWAITING_ADVISER', 'CLOSED')
);

-- Deletion is limited to an unsent/uncompleted workflow state.
drop policy if exists "Adviser can delete own confirmations" on public.confirmation_requests;
create policy "Adviser can delete own confirmations"
on public.confirmation_requests
for delete
to authenticated
using (
  auth.uid() = adviser_id
  and status = 'AWAITING_CLIENT'
);

-- Replace the public read RPC so the first client opening is recorded.
create or replace function public.get_confirmation_by_token(p_token uuid)
returns table (
  reference_no text,
  participant_name text,
  certificate_no text,
  adviser_name text,
  operators jsonb,
  remarks text,
  status text,
  client_signature text,
  client_signed_at timestamptz,
  created_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_confirmation public.confirmation_requests%rowtype;
begin
  select * into v_confirmation
  from public.confirmation_requests c
  where c.public_token = p_token
  limit 1;

  if v_confirmation.id is null then
    return;
  end if;

  if not exists (
    select 1
    from public.confirmation_audit_events a
    where a.confirmation_id = v_confirmation.id
      and a.event_type = 'CLIENT_VIEWED'
  ) then
    insert into public.confirmation_audit_events (
      confirmation_id, adviser_id, event_type, actor_type, actor_label, metadata, occurred_at
    ) values (
      v_confirmation.id,
      v_confirmation.adviser_id,
      'CLIENT_VIEWED',
      'CLIENT',
      v_confirmation.participant_name,
      jsonb_build_object('reference_no', v_confirmation.reference_no),
      now()
    );
  end if;

  return query
  select
    v_confirmation.reference_no,
    v_confirmation.participant_name,
    v_confirmation.certificate_no,
    v_confirmation.adviser_name,
    v_confirmation.operators,
    v_confirmation.remarks,
    v_confirmation.status,
    v_confirmation.client_signature,
    v_confirmation.client_signed_at,
    v_confirmation.created_at;
end;
$$;

-- Replace the client submission RPC so signing is recorded in the append-only audit table.
create or replace function public.submit_client_confirmation(
  p_token uuid,
  p_signature text
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_now timestamptz := now();
  v_id uuid;
  v_adviser_id uuid;
  v_reference_no text;
  v_participant_name text;
begin
  if p_signature is null or length(p_signature) < 100 then
    raise exception 'A valid signature is required';
  end if;

  update public.confirmation_requests
  set
    client_signature = p_signature,
    client_signed_at = v_now,
    status = 'AWAITING_ADVISER',
    updated_at = v_now,
    audit_log = coalesce(audit_log, '[]'::jsonb) || jsonb_build_array(
      jsonb_build_object(
        'action', 'Participant confirmed & signed',
        'timestamp', to_char(v_now at time zone 'Asia/Kuala_Lumpur', 'DD/MM/YYYY, HH24:MI:SS')
      )
    )
  where public_token = p_token
    and status = 'AWAITING_CLIENT'
  returning id, adviser_id, reference_no, participant_name
  into v_id, v_adviser_id, v_reference_no, v_participant_name;

  if v_id is null then
    return false;
  end if;

  insert into public.confirmation_audit_events (
    confirmation_id, adviser_id, event_type, actor_type, actor_label, metadata, occurred_at
  ) values (
    v_id,
    v_adviser_id,
    'CLIENT_SIGNED',
    'CLIENT',
    v_participant_name,
    jsonb_build_object('reference_no', v_reference_no),
    v_now
  );

  return true;
end;
$$;

revoke all on function public.get_confirmation_by_token(uuid) from public;
revoke all on function public.submit_client_confirmation(uuid, text) from public;
grant execute on function public.get_confirmation_by_token(uuid) to anon, authenticated;
grant execute on function public.submit_client_confirmation(uuid, text) to anon, authenticated;
